# Generated by Django 4.0.4 on 2022-05-31 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=255, verbose_name='Название товара')),
                ('price', models.ImageField(default=0, upload_to='', verbose_name='цена')),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='upload/products', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
